server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/com_sys?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#旧驱动无法使用更换成新的:com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      properties:
          hibernate:
              hbm2ddl:
                  auto: update
      hibernate:
          ddl-auto: update
      show-sql: true
  activemq:
    broker-url: tcp://10.10.32.188:61616
    user: mqs_app
    password: UhJpwTULAJudpFvC1DXL
    close-timeout: 15s   # 在考虑结束之前等待的时间
    in-memory: true      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
    queue-name: active.queue.test
    topic-name: active.topic.test
    packages:
        trust-all: true #不配置此项，会报错
  pool:
    enabled: true
    max-connections: 10   #连接池最大连接数
    idle-timeout: 30000   #空闲的连接过期时间，默认为30秒
